### ISSUE TITLE
3.0 rc1，没内核设置选项呀？没内核用不了。

### ISSUE THREAD

**Issue by hhwa22** [Shadowsocks-NET/Qv2ray#10]
3.0 rc1，没内核设置选项呀？没内核用不了。

**Comment by shanoaice** [comment]
哦……这倒是个该说明的问题。内核设置选项现在被移进插件里了。点左上角那个 plugin 按钮，然后在弹出窗口的左边列表里选中 V2Ray Core Plugin，这个时候左边的界面就能设置内核选项了

**Comment by hhwa22** [comment]
感谢，已经搞定了。没想到选项放在插件这里了！！

**Comment by hhwa22** [comment]
太强了！！

**Comment by chenxiccc** [comment]
插件这里，没有v2ray core plugin。请问如何解决呢？
<img width="878" alt="iShot2022-02-11 22 42 13" src="https://user-images.githubusercontent.com/1096853/153612160-285c66ef-a09d-461d-8b5c-ca7eaa344b5e.png">
