### ISSUE TITLE
测速插件在哪里下载呢，找了几个小时了，没找到下载地址。。。实在不好意思啊老哥

### ISSUE THREAD

**Issue by hhwa22** [Shadowsocks-NET/Qv2ray#11]
测速插件在哪里下载呢，找了几个小时了，没找到下载地址。。。实在不好意思啊老哥

**Comment by AkinoKaede** [comment]
没有这个东西吧…

**Comment by shanoaice** [comment]
> 测速插件在哪里下载呢，找了几个小时了，没找到下载地址。。。实在不好意思啊老哥

如果你找的是那个 Test Latency 的话……在[这里](https://github.com/Shadowsocks-NET/QvPlugins), Actions 里面点进去下载对应系统的 Artifact

**Comment by hhwa22** [comment]
> 没有这个东西吧…

这个测速插件是builtin的吧，我的打开之后，没有那个tcping test engine，要测速节点，提示Latency test engine ID is null

**Comment by shanoaice** [comment]
> > 没有这个东西吧…
> 
> 这个测速插件是 builtin 的吧，我的打开之后，没有那个 tcping test engine，要测速节点，提示 Latency test engine ID is null

看我的 Comment... 不一定是 Builtin 的，有些时候你下到的 Release 有有些时候没有，从 ·Shadowsocks-NET/QvPlugins· 的 Actions 里面拿 Artifact，解压那个压缩包在子文件夹里找 `QvPlugin-LatencyTest.dll(.so)` 然后丢进插件文件夹里
