### ISSUE TITLE
大佬，测速全是error，不知道怎么回事

### ISSUE THREAD

**Issue by hhwa22** [Shadowsocks-NET/Qv2ray#13]
正常连接没问题，但测速全是error，怎么解决，大佬

**Comment by shanoaice** [comment]
@hhwa22 没记错的话这个延迟测试引擎是用的 TCPing，连接是是 80（还是 443 来着）端口。如果这个端口上没有东西/防火墙设置没有开放这个端口的话这个延迟测试连接就会被 Reject 掉

**Comment by shanoaice** [comment]
解决方法是不用解决，靠谱的延迟测试方法多了去了，建议用 [Speedtest](speedtest.net), 既能测延迟也能测带宽。

**Comment by database64128** [comment]
The tcping latency tester doesn't work on Windows.
