### ISSUE TITLE
wrong aur package name in the latest release

### ISSUE THREAD

**Issue by syvshc** [Shadowsocks-NET/Qv2ray#16]
> Currently no release artifact for Linux is provided (an AppImage release is planned), for now, Arch Linux users can check out qv2ray-static-nightly-bin in AUR.

However the right package name is qv2ray-static-bin-nightly : https://aur.archlinux.org/packages/qv2ray-static-bin-nightly/

**Comment by shanoaice** [comment]
@syvshc sorry, my fault
I forget to correct the AUR package name

**Comment by syvshc** [comment]
> @syvshc sorry, my fault I forget to correct the AUR package name

Thanks, I'll close this issue and thanks for your contribution.

**Comment by SpriteOvO** [comment]
As [the AUR comment](https://aur.archlinux.org/packages/qv2ray-static-bin-nightly/#pinned-846674) says, the package name has been fallback to `qv2ray-static-nightly-bin`.

Now using `qv2ray-static-bin-nightly` will fail with
```
error: target not found: qv2ray-static-nightly-bin
==> ERROR: 'pacman' failed to install missing dependencies.
```
