### ISSUE TITLE
can't find libicu

### ISSUE THREAD

**Issue by CCCharls** [Shadowsocks-NET/Qv2ray#24]
I tried to open qv2ray but this showed up
`qv2ray: error while loading shared libraries: libicui18n.so.69: cannot open shared object file: No such file or directory`

**Comment by CCCharls** [comment]
_ldd /bin/qv2ray_ showed that 
`	
        libicui18n.so.69 => not found
	libicuuc.so.69 => not found
	libicudata.so.69 => not found
`
_sudo pacman -Ss icu_ showed

`core/icu 70.1-1 [installed]
    International Components for Unicode library`

**Comment by shanoaice** [comment]
@CCCharls hmm, where did you obtain the Qv2ray binary, the release build?

**Comment by CCCharls** [comment]
> @CCCharls hmm, where did you obtain the Qv2ray binary, the release build?

I installed qv2ray from AUR

**Comment by shanoaice** [comment]
@CCCharls that package is way too old (it is actually the archived Qv2ray v2 branch). please use qv2ray-static-bin-nightly package instead.

**Comment by CCCharls** [comment]
> 

nah I used that package, I tried to reinstall it by `paru -S qv2ray-static-bin-nightly` but it's still showing `qv2ray: error while loading shared libraries: libicui18n.so.69: cannot open shared object file: No such file or directory
`

**Comment by CCCharls** [comment]
and I tried to find _libicui18n.so.69_ under my _/usr/lib_ folder but there's only _libcui18n.so.70_ I guess it have something to do with the version or something else

**Comment by shanoaice** [comment]
@CCCharls well, let me report to the maintainer of that package. meanwhile you might try to downgrade libicu to version 69 and see if it break anything (could possibly break lots of packages though)

**Comment by CCCharls** [comment]
> @CCCharls well, let me report to the maintainer of that package. meanwhile you might try to downgrade libicu to version 69 and see if it break anything (could possibly break lots of packages though)

thanks a lot, well I can't really downgrade because there's way many packages than i thought that require the latest version of libicu

**Comment by CCCharls** [comment]
I found a libicu package which is version 69, but I can't install it using _pacman_ cause it will brake a lot of other packages so I just unzip the package and copy all the files to my _/usr_ folder and the problem just gone, qv2ray is now working fine for me.
it was a problem with the version of libicu

**Comment by database64128** [comment]
Fixed by rebuilding "static" Qt. You can now update the AUR package.
