### ISSUE TITLE
Vless Issue

### ISSUE THREAD

**Issue by rootergod** [Shadowsocks-NET/Qv2ray#27]
In the latest version I can not use the Vless protocol What happened?

**Comment by shanoaice** [comment]
@rootergod Any error logs? Also be aware that if you are using Xray-core, you should be expecting issues and we developers are not going to fix them.

**Comment by database64128** [comment]
Support for VLESS has been removed in 3a2566e18bec9f960951ef25466df1ef171efcad. VLESS is basically rebranded Trojan. There's no practical reason to use VLESS.
