### ISSUE TITLE
Qv2ray3.0 内置Trojan支持不能正确解析配置中的SNI

### ISSUE THREAD

**Issue by ryosukeeeeee** [Shadowsocks-NET/Qv2ray#28]
Qv2ray3.0已经将Trojan的支持改为内建直接支持的形式，而不再需要插件。  

在导入Trojan节点，或新建Trojan节点时，如果携带了，或填入了SNI的值，则此节点将不能被解析，生成的Link中没有sni的部分。

此节点已经验证在Qv2ray2.7版本中配合Trojan插件可正常使用。

如果是Qv2ray3.0决定不再支持非[Trojan标准格式](https://github.com/trojan-gfw/trojan-url)的，Trojan分享链接后部中带`?sni=xxx.sni.com#node_name`的形式，可以直接关闭此issue。

**Comment by moodyhunter** [comment]
Fixed in https://github.com/Shadowsocks-NET/Qv2ray/commit/dac7ed1619ae6d3c70041c6d385aec0b76694207, go check out and have a test!

**Comment by ryosukeeeeee** [comment]
It works fine now. Thank you for your great work for linux users.
