### ISSUE TITLE
显示连接后无法上网

### ISSUE THREAD

**Issue by Firestar-Reimu** [Shadowsocks-NET/Qv2ray#29]
![Screenshot_20211227_105546](https://user-images.githubusercontent.com/65082432/147429739-a39f6347-bfff-4548-9a4f-36f507c386da.png)

可以测试延迟，显示连接，但是旁边的图没有流量显示，log也不更新，google/wikipedia等也无法访问

```
System:
  Host: ThinkPad Kernel: 5.15.11-1-MANJARO x86_64 bits: 64
    Desktop: KDE Plasma 5.23.4 Distro: Manjaro Linux
Machine:
  Type: Laptop System: LENOVO product: 20WKA000CD v: ThinkPad X13 Gen 2i
Network:
  Device-1: Intel Ethernet I219-V driver: e1000e
  Device-2: Intel Wi-Fi 6 AX210/AX211/AX411 160MHz driver: iwlwifi
```

**Comment by Firestar-Reimu** [comment]
核心配置应该是`/bin/v2ray`和`/usr/share/v2ray`，但没有报错“找不到v2ray核心”

**Comment by GT-610** [comment]
> 

是 `usr/bin/v2ray` 吧
不过我配置好之后也没法连接

**Comment by Firestar-Reimu** [comment]
```
○ v2ray.service - V2Ray Service
     Loaded: loaded (/usr/lib/systemd/system/v2ray.service; disabled; vendor preset: disabled)
     Active: inactive (dead)
       Docs: https://www.v2fly.org/

Jul 12 01:25:52 ThinkPad systemd[1]: [🡕] /usr/lib/systemd/system/v2ray.service:7: Special user nobody configured, this is not safe!
```

This is `sudo systemctl status v2ray`

**Comment by w3nq14** [comment]
![image](https://user-images.githubusercontent.com/85664099/182578974-9e19a9dd-7539-4caf-b0cc-91e5983ce723.png)
--proxy-server="127.0.0.1:8888"
![image](https://user-images.githubusercontent.com/85664099/182579133-4225f6b6-a9ba-43f4-a788-78faca7f680a.png)

**Comment by Firestar-Reimu** [comment]
所以说绕过中国大陆是坏掉了吗

**Comment by Firestar-Reimu** [comment]
@WHOAMI-xiaoyu 建议你看一下你qv2ray的版本，3.0版本是没有英文的，你肯定用的是2.7

实际上我自己在3.0那里用这个方法也不行
