### ISSUE TITLE
linux版本无法运行

### ISSUE THREAD

**Issue by yinglight** [Shadowsocks-NET/Qv2ray#34]
双击后文件后，选择运行，就没有反应。

**Comment by SamLukeYes** [comment]
如果你能回答以下三个问题，或许其他人会更容易帮助你。

1. 你的发行版是？

2. 你是通过何种途径得到的 qv2ray？比如说是从哪下载的预编译版本，还是从哪个版本的 git 源码编译的？

3. 如果在终端中运行会有什么输出？
