### ISSUE TITLE
Windows CI 不通过

### ISSUE THREAD

**Issue by plusls** [Shadowsocks-NET/Qv2ray#35]
查看历史 CI 时发现，最新的 commit 是可以 pass 掉 windows 的 CI的

https://github.com/Shadowsocks-NET/Qv2ray/actions/runs/1869026203

但是我自己 fork 一份后又跑了一次 CI,发现其它 CI 都能过，就 Windows  过不去，很是疑惑

https://github.com/plusls/Qv2ray/runs/5391744066?check_suite_focus=true

**Comment by dyhkwong** [comment]
`windows-latest` now uses `windows-2022` by default. I don't know why `windows-2022` failed to build, but if you specify `windows-2019`, everything should be okay.

**Comment by moodyhunter** [comment]
fixed in https://github.com/Shadowsocks-NET/Qv2ray/commit/6106d513cc310de19ba5fe313c0203873f1a9cc4, thanks for your report.
