### ISSUE TITLE
Does this version supports Xray?

### ISSUE THREAD

**Issue by Firestar-Reimu** [Shadowsocks-NET/Qv2ray#45]
**Does this version supports Xray?**

[This article](https://v2xtls.org/project-x%E5%86%8D%E7%88%86%E4%B8%8Eqv2ray%E5%BC%80%E5%8F%91%E8%80%85%E5%A4%A7%E7%93%9C/) says after [this commit](https://github.com/Qv2ray/Qv2ray/commit/c20e3378c397ae2cab09b71042e1b1381d0a8859), qv2ray does not support Xray

and [this commit](https://github.com/Qv2ray/Qv2ray/commit/844f79ae6c797f82a07a19aca6ace35f637d9515) says gcc-13(which is also known as gcc) will come back.

I am thinking about whether this version supports Xray

**Comment by FlandiaYingman** [comment]
The commit you referenced is an April's Fools Day joke. (https://github.com/Qv2ray/Qv2ray/commit/844f79ae6c797f82a07a19aca6ace35f637d9515)

The author of this project says the following in the README.md: 

> ### Xray
> No Such Word In My Dictionary

Therefore I guess this project would not support Xray.

**Comment by Firestar-Reimu** [comment]
Thanks! I remember that the former qv2ray 2.7.0 supports Xray
