### ISSUE TITLE
You may need serveral patches to fix the testing

### ISSUE THREAD

**Issue by sixg0000d** [Shadowsocks-NET/Qv2ray#5]
You may need to apply [this patch](https://github.com/sixg0000d-copr/qv2ray/blob/Shadowsocks-NET/0001-update-include-path.patch) to fix unit test building, and [this patch](https://github.com/Qv2ray/Qv2ray/commit/12e508cc5d9a3e9e3eacd91ddd85f5eabb150849.patch) to pass the unit test

**Comment by database64128** [comment]
Thank you for your interest in improving this project. However, since the upstream repo [moodyhunter/QvPersonal](https://github.com/moodyhunter/QvPersonal) is already public, this repo has served its purpose, and will soon be archived. You may submit your patches directly to the upstream.

**Comment by sixg0000d** [comment]
> Thank you for your interest in improving this project. However, since the upstream repo [moodyhunter/QvPersonal](https://github.com/moodyhunter/QvPersonal) is already public, this repo has served its purpose, and will soon be archived. You may submit your patches directly to the upstream.

OK, thanks for your reply. And there is no unit test in [moodyhunter/QvPersonal](https://github.com/moodyhunter/QvPersonal) anymore, so these patches was unnecessary to this fork.

**Comment by database64128** [comment]
Thank you for your patch proposal. These patches have been applied.
