### ISSUE TITLE
Compatible with v2ray 5.0.7?

### ISSUE THREAD

**Issue by playgithub** [Shadowsocks-NET/Qv2ray#50]
There is an important security enhancement in v2ray 5.0.7, see https://github.com/v2fly/v2ray-core/releases

I've tried Qv2ray 2.7.0 at https://github.com/Qv2ray/Qv2ray/releases/tag/v2.7.0, it is not compatible with v2ray 5.0.4

Is Qv2ray 3.0.0-rc1 compatible with v2ray 5.0.7?

**Comment by playgithub** [comment]
I've tried Qv2ray 3.0.0-rc1 with v2ray 5.0.7-preview on Windows.
It works.
BTW, Qv2ray doesn't set/unset system proxy, so it needs to be set/unset manually.

**Comment by database64128** [comment]
The rc1 release is outdated and may have bugs. You should use the latest binaries from CI.
