### ISSUE TITLE
System proxy can't be set/unset automatically anymore

### ISSUE THREAD

**Issue by playgithub** [Shadowsocks-NET/Qv2ray#51]
### Version Info
* OS<br>Windows 11 
* Qv2ray<br>https://github.com/Shadowsocks-NET/Qv2ray/actions
https://github.com/Shadowsocks-NET/Qv2ray/suites/7124057466/artifacts/282776052

### Problem
* After connecting, system proxy is not set automatically
* After disconnecting, system proxy is not unset automatically

### More Info
* If set system proxy manually, it works.
* For Qv2ray 2.7.0 (https://github.com/Qv2ray/Qv2ray), system proxy can be set/unset automatically.

**Comment by playgithub** [comment]
Codes that set system proxy: https://github.com/Qv2ray/Qv2ray/blob/844f79ae6c797f82a07a19aca6ace35f637d9515/src/components/proxy/QvProxyConfigurator.cpp#L249

**Comment by playgithub** [comment]
@dyhkwong Thanks a lot

**Comment by database64128** [comment]
Although the feature was intentionally removed in the past, the maintainer is probably willing to accept a PR that adds it back.
