### ISSUE TITLE
要如何支持ssr呢?

### ISSUE THREAD

**Issue by aavamin** [Shadowsocks-NET/Qv2ray#56]
要如何支持ssr呢?

**Comment by shanoaice** [comment]
SSR 棺材板早就给钉死了，Shadowsocks-NET 的 Qv2ray 3.0 现在没有，将来也大概率不会有支持 SSR 的计划

**Comment by aavamin** [comment]
> SSR 棺材板早就给钉死了，Shadowsocks-NET 的 Qv2ray 3.0 现在没有，将来也大概率不会有支持 SSR 的计划

好的，因为我购买的机场不知道为什么用3.0连不上ss，只能用ssr，感谢回复！
