### ISSUE TITLE
现在应该如何下载qv2ray？

### ISSUE THREAD

**Issue by Firestar-Reimu** [Shadowsocks-NET/Qv2ray#58]
旧的qv2ray 2.7 不支持 v2ray5，qv2ray-git是过期包，qv2ray-static-bin-nightly没了

克隆qv2ray-git的时候：
```
Cloning into bare repository '/home/firestar/.cache/yay/qv2ray-git/qv2ray-git'...
  0     0    0     0    0     0      0      0 --:--:--  0:00:59 --:--:--     0
```
速度为零

反正很矛盾的事情就是“你需要翻墙才能获得翻墙工具”

**Comment by database64128** [comment]
The Qv2ray project is essentially dead. Even V2Ray hasn't seen much progress being made and is becoming increasingly unmaintainable. I suggest you switch to one of the new implementations (no GUIs, of course):

- https://github.com/SagerNet/sing-box
- https://github.com/database64128/shadowsocks-go

**Comment by Firestar-Reimu** [comment]
Thanks! I will switch to v2rayA (which I spent one whole day to know how to configure it) for a while. Maybe I will use sing-box later.

主要是我试过了qv2ray-git (v3.0, from AUR) + v2ray 5.1，根本不能用，还是这个问题 https://github.com/Shadowsocks-NET/Qv2ray/issues/29
