### ISSUE TITLE
Running latest version will break exist configuration files

### ISSUE THREAD

**Issue by SmartPolarBear** [Shadowsocks-NET/Qv2ray#6]
Running latest version from [Actions](https://github.com/Shadowsocks-NET/Qv2ray/actions) will make existing configurations like subscriptions and links completely a mess.

**Comment by up-upeveryday** [comment]
I recommended  v2.7.0 pre2 version which works best both on v2ray and xray.
https://github.com/Qv2ray/Qv2ray/releases/tag/v2.7.0-pre2

**Comment by database64128** [comment]
The developer made multiple breaking changes to the config format without backwards compatibility in mind. Just delete the old config and start fresh.
